"""
DreamHome Studio Catalog Dataset — Commercial Workspace Systems
Provides detailed production specifications, dimensions, materials, and pricing.
"""

CATALOG_ITEMS_COMMERCIAL_WORKSPACE_SYSTEMS = [
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 001",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0001",
        "brand": "Steelcase",
        "width_cm": 85.0,
        "depth_cm": 64.0,
        "height_cm": 78.0,
        "price": 485.5,
        "material": "Aluminum",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 106.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 002",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0002",
        "brand": "HermanMiller",
        "width_cm": 90.0,
        "depth_cm": 68.0,
        "height_cm": 81.0,
        "price": 521.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 123.9,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 003",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0003",
        "brand": "Knoll",
        "width_cm": 95.0,
        "depth_cm": 72.0,
        "height_cm": 84.0,
        "price": 556.5,
        "material": "Laminate",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 143.6,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 004",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0004",
        "brand": "Haworth",
        "width_cm": 100.0,
        "depth_cm": 76.0,
        "height_cm": 87.0,
        "price": 592.0,
        "material": "Tempered Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 165.3,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 005",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0005",
        "brand": "ExecutiveWork",
        "width_cm": 105.0,
        "depth_cm": 80.0,
        "height_cm": 90.0,
        "price": 627.5,
        "material": "Steel",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 189.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 006",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0006",
        "brand": "Steelcase",
        "width_cm": 110.0,
        "depth_cm": 84.0,
        "height_cm": 93.0,
        "price": 663.0,
        "material": "Aluminum",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 214.8,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 007",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0007",
        "brand": "HermanMiller",
        "width_cm": 115.0,
        "depth_cm": 88.0,
        "height_cm": 96.0,
        "price": 698.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 242.9,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 008",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0008",
        "brand": "Knoll",
        "width_cm": 120.0,
        "depth_cm": 92.0,
        "height_cm": 99.0,
        "price": 734.0,
        "material": "Laminate",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 273.2,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 009",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0009",
        "brand": "Haworth",
        "width_cm": 125.0,
        "depth_cm": 96.0,
        "height_cm": 102.0,
        "price": 769.5,
        "material": "Tempered Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 306.0,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 010",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0010",
        "brand": "ExecutiveWork",
        "width_cm": 130.0,
        "depth_cm": 100.0,
        "height_cm": 105.0,
        "price": 805.0,
        "material": "Steel",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 341.2,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 011",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0011",
        "brand": "Steelcase",
        "width_cm": 135.0,
        "depth_cm": 104.0,
        "height_cm": 108.0,
        "price": 840.5,
        "material": "Aluminum",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 379.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 012",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0012",
        "brand": "HermanMiller",
        "width_cm": 140.0,
        "depth_cm": 108.0,
        "height_cm": 111.0,
        "price": 876.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 419.6,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 013",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0013",
        "brand": "Knoll",
        "width_cm": 145.0,
        "depth_cm": 112.0,
        "height_cm": 114.0,
        "price": 911.5,
        "material": "Laminate",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 462.8,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 014",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0014",
        "brand": "Haworth",
        "width_cm": 150.0,
        "depth_cm": 116.0,
        "height_cm": 117.0,
        "price": 947.0,
        "material": "Tempered Glass",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 508.9,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 015",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0015",
        "brand": "ExecutiveWork",
        "width_cm": 155.0,
        "depth_cm": 120.0,
        "height_cm": 120.0,
        "price": 982.5,
        "material": "Steel",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 558.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 016",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0016",
        "brand": "Steelcase",
        "width_cm": 160.0,
        "depth_cm": 124.0,
        "height_cm": 123.0,
        "price": 1018.0,
        "material": "Aluminum",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 610.1,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 017",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0017",
        "brand": "HermanMiller",
        "width_cm": 165.0,
        "depth_cm": 128.0,
        "height_cm": 126.0,
        "price": 1053.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 665.3,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 018",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0018",
        "brand": "Knoll",
        "width_cm": 170.0,
        "depth_cm": 132.0,
        "height_cm": 129.0,
        "price": 1089.0,
        "material": "Laminate",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 723.7,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 019",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0019",
        "brand": "Haworth",
        "width_cm": 175.0,
        "depth_cm": 136.0,
        "height_cm": 132.0,
        "price": 1124.5,
        "material": "Tempered Glass",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 785.4,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 020",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0020",
        "brand": "ExecutiveWork",
        "width_cm": 180.0,
        "depth_cm": 140.0,
        "height_cm": 135.0,
        "price": 1160.0,
        "material": "Steel",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 850.5,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 021",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0021",
        "brand": "Steelcase",
        "width_cm": 185.0,
        "depth_cm": 144.0,
        "height_cm": 138.0,
        "price": 1195.5,
        "material": "Aluminum",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 919.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 022",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0022",
        "brand": "HermanMiller",
        "width_cm": 190.0,
        "depth_cm": 148.0,
        "height_cm": 141.0,
        "price": 1231.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 991.2,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 023",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0023",
        "brand": "Knoll",
        "width_cm": 195.0,
        "depth_cm": 152.0,
        "height_cm": 144.0,
        "price": 1266.5,
        "material": "Laminate",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1067.0,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 024",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0024",
        "brand": "Haworth",
        "width_cm": 200.0,
        "depth_cm": 156.0,
        "height_cm": 147.0,
        "price": 1302.0,
        "material": "Tempered Glass",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1146.6,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 025",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0025",
        "brand": "ExecutiveWork",
        "width_cm": 205.0,
        "depth_cm": 160.0,
        "height_cm": 150.0,
        "price": 1337.5,
        "material": "Steel",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1230.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 026",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0026",
        "brand": "Steelcase",
        "width_cm": 210.0,
        "depth_cm": 164.0,
        "height_cm": 153.0,
        "price": 1373.0,
        "material": "Aluminum",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1317.3,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 027",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0027",
        "brand": "HermanMiller",
        "width_cm": 215.0,
        "depth_cm": 168.0,
        "height_cm": 156.0,
        "price": 1408.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1408.7,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 028",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0028",
        "brand": "Knoll",
        "width_cm": 220.0,
        "depth_cm": 172.0,
        "height_cm": 159.0,
        "price": 1444.0,
        "material": "Laminate",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1504.1,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 029",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0029",
        "brand": "Haworth",
        "width_cm": 225.0,
        "depth_cm": 176.0,
        "height_cm": 162.0,
        "price": 1479.5,
        "material": "Tempered Glass",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1603.8,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 030",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0030",
        "brand": "ExecutiveWork",
        "width_cm": 230.0,
        "depth_cm": 180.0,
        "height_cm": 165.0,
        "price": 1515.0,
        "material": "Steel",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1707.8,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 031",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0031",
        "brand": "Steelcase",
        "width_cm": 235.0,
        "depth_cm": 184.0,
        "height_cm": 168.0,
        "price": 1550.5,
        "material": "Aluminum",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1816.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 032",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0032",
        "brand": "HermanMiller",
        "width_cm": 240.0,
        "depth_cm": 188.0,
        "height_cm": 171.0,
        "price": 1586.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1928.9,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 033",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0033",
        "brand": "Knoll",
        "width_cm": 245.0,
        "depth_cm": 192.0,
        "height_cm": 174.0,
        "price": 1621.5,
        "material": "Laminate",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2046.2,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 034",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0034",
        "brand": "Haworth",
        "width_cm": 250.0,
        "depth_cm": 196.0,
        "height_cm": 177.0,
        "price": 1657.0,
        "material": "Tempered Glass",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2168.2,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 035",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0035",
        "brand": "ExecutiveWork",
        "width_cm": 255.0,
        "depth_cm": 200.0,
        "height_cm": 180.0,
        "price": 1692.5,
        "material": "Steel",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2295.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 036",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0036",
        "brand": "Steelcase",
        "width_cm": 260.0,
        "depth_cm": 204.0,
        "height_cm": 183.0,
        "price": 1728.0,
        "material": "Aluminum",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2426.6,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 037",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0037",
        "brand": "HermanMiller",
        "width_cm": 265.0,
        "depth_cm": 208.0,
        "height_cm": 186.0,
        "price": 1763.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2563.1,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 038",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0038",
        "brand": "Knoll",
        "width_cm": 270.0,
        "depth_cm": 212.0,
        "height_cm": 189.0,
        "price": 1799.0,
        "material": "Laminate",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2704.6,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 039",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0039",
        "brand": "Haworth",
        "width_cm": 275.0,
        "depth_cm": 216.0,
        "height_cm": 192.0,
        "price": 1834.5,
        "material": "Tempered Glass",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2851.2,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 040",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0040",
        "brand": "ExecutiveWork",
        "width_cm": 280.0,
        "depth_cm": 220.0,
        "height_cm": 195.0,
        "price": 1870.0,
        "material": "Steel",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3003.0,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 041",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0041",
        "brand": "Steelcase",
        "width_cm": 285.0,
        "depth_cm": 224.0,
        "height_cm": 198.0,
        "price": 1905.5,
        "material": "Aluminum",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3160.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 042",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0042",
        "brand": "HermanMiller",
        "width_cm": 290.0,
        "depth_cm": 228.0,
        "height_cm": 201.0,
        "price": 1941.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3322.5,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 043",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0043",
        "brand": "Knoll",
        "width_cm": 295.0,
        "depth_cm": 232.0,
        "height_cm": 204.0,
        "price": 1976.5,
        "material": "Laminate",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3490.4,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 044",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0044",
        "brand": "Haworth",
        "width_cm": 300.0,
        "depth_cm": 236.0,
        "height_cm": 207.0,
        "price": 2012.0,
        "material": "Tempered Glass",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3663.9,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 045",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0045",
        "brand": "ExecutiveWork",
        "width_cm": 305.0,
        "depth_cm": 240.0,
        "height_cm": 210.0,
        "price": 2047.5,
        "material": "Steel",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 3843.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 046",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0046",
        "brand": "Steelcase",
        "width_cm": 310.0,
        "depth_cm": 244.0,
        "height_cm": 213.0,
        "price": 2083.0,
        "material": "Aluminum",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 4027.8,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 047",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0047",
        "brand": "HermanMiller",
        "width_cm": 315.0,
        "depth_cm": 248.0,
        "height_cm": 216.0,
        "price": 2118.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 4218.5,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 048",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0048",
        "brand": "Knoll",
        "width_cm": 320.0,
        "depth_cm": 252.0,
        "height_cm": 219.0,
        "price": 2154.0,
        "material": "Laminate",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 4415.0,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 049",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0049",
        "brand": "Haworth",
        "width_cm": 325.0,
        "depth_cm": 256.0,
        "height_cm": 222.0,
        "price": 2189.5,
        "material": "Tempered Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 4617.6,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 050",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0050",
        "brand": "ExecutiveWork",
        "width_cm": 330.0,
        "depth_cm": 60.0,
        "height_cm": 225.0,
        "price": 2225.0,
        "material": "Steel",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1113.8,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 051",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0051",
        "brand": "Steelcase",
        "width_cm": 335.0,
        "depth_cm": 64.0,
        "height_cm": 228.0,
        "price": 2260.5,
        "material": "Aluminum",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1222.1,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 052",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0052",
        "brand": "HermanMiller",
        "width_cm": 340.0,
        "depth_cm": 68.0,
        "height_cm": 231.0,
        "price": 2296.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1335.2,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 053",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0053",
        "brand": "Knoll",
        "width_cm": 345.0,
        "depth_cm": 72.0,
        "height_cm": 234.0,
        "price": 2331.5,
        "material": "Laminate",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1453.1,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 054",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0054",
        "brand": "Haworth",
        "width_cm": 350.0,
        "depth_cm": 76.0,
        "height_cm": 237.0,
        "price": 2367.0,
        "material": "Tempered Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1576.0,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 055",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0055",
        "brand": "ExecutiveWork",
        "width_cm": 355.0,
        "depth_cm": 80.0,
        "height_cm": 240.0,
        "price": 2402.5,
        "material": "Steel",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1704.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 056",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0056",
        "brand": "Steelcase",
        "width_cm": 360.0,
        "depth_cm": 84.0,
        "height_cm": 243.0,
        "price": 2438.0,
        "material": "Aluminum",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1837.1,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 057",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0057",
        "brand": "HermanMiller",
        "width_cm": 365.0,
        "depth_cm": 88.0,
        "height_cm": 246.0,
        "price": 2473.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1975.4,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 058",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0058",
        "brand": "Knoll",
        "width_cm": 370.0,
        "depth_cm": 92.0,
        "height_cm": 249.0,
        "price": 2509.0,
        "material": "Laminate",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2119.0,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 059",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0059",
        "brand": "Haworth",
        "width_cm": 375.0,
        "depth_cm": 96.0,
        "height_cm": 252.0,
        "price": 2544.5,
        "material": "Tempered Glass",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2268.0,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 060",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0060",
        "brand": "ExecutiveWork",
        "width_cm": 80.0,
        "depth_cm": 100.0,
        "height_cm": 255.0,
        "price": 2580.0,
        "material": "Steel",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 510.0,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 061",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0061",
        "brand": "Steelcase",
        "width_cm": 85.0,
        "depth_cm": 104.0,
        "height_cm": 258.0,
        "price": 2615.5,
        "material": "Aluminum",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 570.2,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 062",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0062",
        "brand": "HermanMiller",
        "width_cm": 90.0,
        "depth_cm": 108.0,
        "height_cm": 261.0,
        "price": 2651.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 634.2,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 063",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0063",
        "brand": "Knoll",
        "width_cm": 95.0,
        "depth_cm": 112.0,
        "height_cm": 264.0,
        "price": 2686.5,
        "material": "Laminate",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 702.2,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 064",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0064",
        "brand": "Haworth",
        "width_cm": 100.0,
        "depth_cm": 116.0,
        "height_cm": 267.0,
        "price": 2722.0,
        "material": "Tempered Glass",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 774.3,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 065",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0065",
        "brand": "ExecutiveWork",
        "width_cm": 105.0,
        "depth_cm": 120.0,
        "height_cm": 270.0,
        "price": 2757.5,
        "material": "Steel",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 850.5,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 066",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0066",
        "brand": "Steelcase",
        "width_cm": 110.0,
        "depth_cm": 124.0,
        "height_cm": 273.0,
        "price": 2793.0,
        "material": "Aluminum",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 930.9,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 067",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0067",
        "brand": "HermanMiller",
        "width_cm": 115.0,
        "depth_cm": 128.0,
        "height_cm": 276.0,
        "price": 2828.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1015.7,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 068",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0068",
        "brand": "Knoll",
        "width_cm": 120.0,
        "depth_cm": 132.0,
        "height_cm": 279.0,
        "price": 2864.0,
        "material": "Laminate",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1104.8,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 069",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0069",
        "brand": "Haworth",
        "width_cm": 125.0,
        "depth_cm": 136.0,
        "height_cm": 282.0,
        "price": 2899.5,
        "material": "Tempered Glass",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1198.5,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 070",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0070",
        "brand": "ExecutiveWork",
        "width_cm": 130.0,
        "depth_cm": 140.0,
        "height_cm": 285.0,
        "price": 2935.0,
        "material": "Steel",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1296.8,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 071",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0071",
        "brand": "Steelcase",
        "width_cm": 135.0,
        "depth_cm": 144.0,
        "height_cm": 288.0,
        "price": 2970.5,
        "material": "Aluminum",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1399.7,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 072",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0072",
        "brand": "HermanMiller",
        "width_cm": 140.0,
        "depth_cm": 148.0,
        "height_cm": 291.0,
        "price": 3006.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1507.4,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 073",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0073",
        "brand": "Knoll",
        "width_cm": 145.0,
        "depth_cm": 152.0,
        "height_cm": 294.0,
        "price": 3041.5,
        "material": "Laminate",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1619.9,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 074",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0074",
        "brand": "Haworth",
        "width_cm": 150.0,
        "depth_cm": 156.0,
        "height_cm": 77.0,
        "price": 3077.0,
        "material": "Tempered Glass",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 450.4,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 075",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0075",
        "brand": "ExecutiveWork",
        "width_cm": 155.0,
        "depth_cm": 160.0,
        "height_cm": 80.0,
        "price": 3112.5,
        "material": "Steel",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 496.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 076",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0076",
        "brand": "Steelcase",
        "width_cm": 160.0,
        "depth_cm": 164.0,
        "height_cm": 83.0,
        "price": 3148.0,
        "material": "Aluminum",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 544.5,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 077",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0077",
        "brand": "HermanMiller",
        "width_cm": 165.0,
        "depth_cm": 168.0,
        "height_cm": 86.0,
        "price": 3183.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 596.0,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 078",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0078",
        "brand": "Knoll",
        "width_cm": 170.0,
        "depth_cm": 172.0,
        "height_cm": 89.0,
        "price": 3219.0,
        "material": "Laminate",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 650.6,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 079",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0079",
        "brand": "Haworth",
        "width_cm": 175.0,
        "depth_cm": 176.0,
        "height_cm": 92.0,
        "price": 3254.5,
        "material": "Tempered Glass",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 708.4,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 080",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0080",
        "brand": "ExecutiveWork",
        "width_cm": 180.0,
        "depth_cm": 180.0,
        "height_cm": 95.0,
        "price": 3290.0,
        "material": "Steel",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 769.5,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 081",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0081",
        "brand": "Steelcase",
        "width_cm": 185.0,
        "depth_cm": 184.0,
        "height_cm": 98.0,
        "price": 3325.5,
        "material": "Aluminum",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 834.0,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 082",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0082",
        "brand": "HermanMiller",
        "width_cm": 190.0,
        "depth_cm": 188.0,
        "height_cm": 101.0,
        "price": 3361.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 901.9,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 083",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0083",
        "brand": "Knoll",
        "width_cm": 195.0,
        "depth_cm": 192.0,
        "height_cm": 104.0,
        "price": 3396.5,
        "material": "Laminate",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 973.4,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 084",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0084",
        "brand": "Haworth",
        "width_cm": 200.0,
        "depth_cm": 196.0,
        "height_cm": 107.0,
        "price": 3432.0,
        "material": "Tempered Glass",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1048.6,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 085",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0085",
        "brand": "ExecutiveWork",
        "width_cm": 205.0,
        "depth_cm": 200.0,
        "height_cm": 110.0,
        "price": 3467.5,
        "material": "Steel",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1127.5,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 086",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0086",
        "brand": "Steelcase",
        "width_cm": 210.0,
        "depth_cm": 204.0,
        "height_cm": 113.0,
        "price": 3503.0,
        "material": "Aluminum",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1210.2,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 087",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0087",
        "brand": "HermanMiller",
        "width_cm": 215.0,
        "depth_cm": 208.0,
        "height_cm": 116.0,
        "price": 3538.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1296.9,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 088",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0088",
        "brand": "Knoll",
        "width_cm": 220.0,
        "depth_cm": 212.0,
        "height_cm": 119.0,
        "price": 3574.0,
        "material": "Laminate",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1387.5,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 089",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0089",
        "brand": "Haworth",
        "width_cm": 225.0,
        "depth_cm": 216.0,
        "height_cm": 122.0,
        "price": 3609.5,
        "material": "Tempered Glass",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1482.3,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 090",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0090",
        "brand": "ExecutiveWork",
        "width_cm": 230.0,
        "depth_cm": 220.0,
        "height_cm": 125.0,
        "price": 3645.0,
        "material": "Steel",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1581.2,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 091",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0091",
        "brand": "Steelcase",
        "width_cm": 235.0,
        "depth_cm": 224.0,
        "height_cm": 128.0,
        "price": 3680.5,
        "material": "Aluminum",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1684.5,
        "assembly_required": False,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 092",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0092",
        "brand": "HermanMiller",
        "width_cm": 240.0,
        "depth_cm": 228.0,
        "height_cm": 131.0,
        "price": 3716.0,
        "material": "Acoustic Fabric",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1792.1,
        "assembly_required": True,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 093",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0093",
        "brand": "Knoll",
        "width_cm": 245.0,
        "depth_cm": 232.0,
        "height_cm": 134.0,
        "price": 3751.5,
        "material": "Laminate",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 1904.1,
        "assembly_required": False,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 094",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0094",
        "brand": "Haworth",
        "width_cm": 250.0,
        "depth_cm": 236.0,
        "height_cm": 137.0,
        "price": 3787.0,
        "material": "Tempered Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2020.8,
        "assembly_required": True,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.8
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 095",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0095",
        "brand": "ExecutiveWork",
        "width_cm": 255.0,
        "depth_cm": 240.0,
        "height_cm": 140.0,
        "price": 3822.5,
        "material": "Steel",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2142.0,
        "assembly_required": False,
        "warranty_years": 10,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.9
    },
    {
        "name": "Steelcase Executive Aluminum Workspace Systems Suite Model 096",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0096",
        "brand": "Steelcase",
        "width_cm": 260.0,
        "depth_cm": 244.0,
        "height_cm": 143.0,
        "price": 3858.0,
        "material": "Aluminum",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Steelcase for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2268.0,
        "assembly_required": True,
        "warranty_years": 11,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "HermanMiller Executive Acoustic Fabric Workspace Systems Suite Model 097",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0097",
        "brand": "HermanMiller",
        "width_cm": 265.0,
        "depth_cm": 248.0,
        "height_cm": 146.0,
        "price": 3893.5,
        "material": "Acoustic Fabric",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by HermanMiller for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2398.8,
        "assembly_required": False,
        "warranty_years": 12,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Knoll Executive Laminate Workspace Systems Suite Model 098",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0098",
        "brand": "Knoll",
        "width_cm": 270.0,
        "depth_cm": 252.0,
        "height_cm": 149.0,
        "price": 3929.0,
        "material": "Laminate",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Knoll for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2534.5,
        "assembly_required": True,
        "warranty_years": 13,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Haworth Executive Tempered Glass Workspace Systems Suite Model 099",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0099",
        "brand": "Haworth",
        "width_cm": 275.0,
        "depth_cm": 256.0,
        "height_cm": 152.0,
        "price": 3964.5,
        "material": "Tempered Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by Haworth for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 2675.2,
        "assembly_required": False,
        "warranty_years": 14,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "ExecutiveWork Executive Steel Workspace Systems Suite Model 100",
        "category": "Commercial",
        "subcategory": "Workspace Systems",
        "sku": "SKU-COM-WOR-0100",
        "brand": "ExecutiveWork",
        "width_cm": 280.0,
        "depth_cm": 60.0,
        "height_cm": 155.0,
        "price": 4000.0,
        "material": "Steel",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "Enterprise grade commercial commercial workspace systems engineered by ExecutiveWork for high density ergonomic workplace and hotel suite environments.",
        "weight_kg": 651.0,
        "assembly_required": True,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "commercial_workspace_systems",
        "acoustic_absorption_coef": 0.6
    },
]
