"""
DreamHome Studio Catalog Dataset — Office Desks
Provides detailed production specifications, dimensions, materials, and pricing.
"""

CATALOG_ITEMS_OFFICE_DESKS = [
    {
        "name": "Nordic Premium Walnut Desk Model 001",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0001",
        "brand": "Nordic",
        "width_cm": 53.0,
        "depth_cm": 42.0,
        "height_cm": 34.0,
        "price": 168.5,
        "material": "Walnut",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 15.1,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Milano Premium Steel Desk Model 002",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0002",
        "brand": "Milano",
        "width_cm": 56.0,
        "depth_cm": 44.0,
        "height_cm": 38.0,
        "price": 187.0,
        "material": "Steel",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 18.7,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Artisan Premium Glass Desk Model 003",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0003",
        "brand": "Artisan",
        "width_cm": 59.0,
        "depth_cm": 46.0,
        "height_cm": 42.0,
        "price": 205.5,
        "material": "Glass",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 22.8,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Klassik Premium Laminate Desk Model 004",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0004",
        "brand": "Klassik",
        "width_cm": 62.0,
        "depth_cm": 48.0,
        "height_cm": 46.0,
        "price": 224.0,
        "material": "Laminate",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 27.4,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Studio Premium Oak Desk Model 005",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0005",
        "brand": "Studio",
        "width_cm": 65.0,
        "depth_cm": 50.0,
        "height_cm": 50.0,
        "price": 242.5,
        "material": "Oak",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 32.5,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Nordic Premium Walnut Desk Model 006",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0006",
        "brand": "Nordic",
        "width_cm": 68.0,
        "depth_cm": 52.0,
        "height_cm": 54.0,
        "price": 261.0,
        "material": "Walnut",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 38.2,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Milano Premium Steel Desk Model 007",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0007",
        "brand": "Milano",
        "width_cm": 71.0,
        "depth_cm": 54.0,
        "height_cm": 58.0,
        "price": 279.5,
        "material": "Steel",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 44.5,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Artisan Premium Glass Desk Model 008",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0008",
        "brand": "Artisan",
        "width_cm": 74.0,
        "depth_cm": 56.0,
        "height_cm": 62.0,
        "price": 298.0,
        "material": "Glass",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 51.4,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Klassik Premium Laminate Desk Model 009",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0009",
        "brand": "Klassik",
        "width_cm": 77.0,
        "depth_cm": 58.0,
        "height_cm": 66.0,
        "price": 316.5,
        "material": "Laminate",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 59.0,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Studio Premium Oak Desk Model 010",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0010",
        "brand": "Studio",
        "width_cm": 80.0,
        "depth_cm": 60.0,
        "height_cm": 70.0,
        "price": 335.0,
        "material": "Oak",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 67.2,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Nordic Premium Walnut Desk Model 011",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0011",
        "brand": "Nordic",
        "width_cm": 83.0,
        "depth_cm": 62.0,
        "height_cm": 74.0,
        "price": 353.5,
        "material": "Walnut",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 76.2,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Milano Premium Steel Desk Model 012",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0012",
        "brand": "Milano",
        "width_cm": 86.0,
        "depth_cm": 64.0,
        "height_cm": 78.0,
        "price": 372.0,
        "material": "Steel",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 85.9,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Artisan Premium Glass Desk Model 013",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0013",
        "brand": "Artisan",
        "width_cm": 89.0,
        "depth_cm": 66.0,
        "height_cm": 82.0,
        "price": 390.5,
        "material": "Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 96.3,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Klassik Premium Laminate Desk Model 014",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0014",
        "brand": "Klassik",
        "width_cm": 92.0,
        "depth_cm": 68.0,
        "height_cm": 86.0,
        "price": 409.0,
        "material": "Laminate",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 107.6,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Studio Premium Oak Desk Model 015",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0015",
        "brand": "Studio",
        "width_cm": 95.0,
        "depth_cm": 70.0,
        "height_cm": 90.0,
        "price": 427.5,
        "material": "Oak",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 119.7,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Nordic Premium Walnut Desk Model 016",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0016",
        "brand": "Nordic",
        "width_cm": 98.0,
        "depth_cm": 72.0,
        "height_cm": 94.0,
        "price": 446.0,
        "material": "Walnut",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 132.7,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Milano Premium Steel Desk Model 017",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0017",
        "brand": "Milano",
        "width_cm": 101.0,
        "depth_cm": 74.0,
        "height_cm": 98.0,
        "price": 464.5,
        "material": "Steel",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 146.5,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Artisan Premium Glass Desk Model 018",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0018",
        "brand": "Artisan",
        "width_cm": 104.0,
        "depth_cm": 76.0,
        "height_cm": 102.0,
        "price": 483.0,
        "material": "Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 161.2,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Klassik Premium Laminate Desk Model 019",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0019",
        "brand": "Klassik",
        "width_cm": 107.0,
        "depth_cm": 78.0,
        "height_cm": 106.0,
        "price": 501.5,
        "material": "Laminate",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 176.9,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Studio Premium Oak Desk Model 020",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0020",
        "brand": "Studio",
        "width_cm": 110.0,
        "depth_cm": 80.0,
        "height_cm": 110.0,
        "price": 520.0,
        "material": "Oak",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 193.6,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Nordic Premium Walnut Desk Model 021",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0021",
        "brand": "Nordic",
        "width_cm": 113.0,
        "depth_cm": 82.0,
        "height_cm": 114.0,
        "price": 538.5,
        "material": "Walnut",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 211.3,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Milano Premium Steel Desk Model 022",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0022",
        "brand": "Milano",
        "width_cm": 116.0,
        "depth_cm": 84.0,
        "height_cm": 118.0,
        "price": 557.0,
        "material": "Steel",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 230.0,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Artisan Premium Glass Desk Model 023",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0023",
        "brand": "Artisan",
        "width_cm": 119.0,
        "depth_cm": 86.0,
        "height_cm": 122.0,
        "price": 575.5,
        "material": "Glass",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 249.7,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Klassik Premium Laminate Desk Model 024",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0024",
        "brand": "Klassik",
        "width_cm": 122.0,
        "depth_cm": 88.0,
        "height_cm": 126.0,
        "price": 594.0,
        "material": "Laminate",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 270.5,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Studio Premium Oak Desk Model 025",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0025",
        "brand": "Studio",
        "width_cm": 125.0,
        "depth_cm": 90.0,
        "height_cm": 130.0,
        "price": 612.5,
        "material": "Oak",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 292.5,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Nordic Premium Walnut Desk Model 026",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0026",
        "brand": "Nordic",
        "width_cm": 128.0,
        "depth_cm": 92.0,
        "height_cm": 134.0,
        "price": 631.0,
        "material": "Walnut",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 315.6,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Milano Premium Steel Desk Model 027",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0027",
        "brand": "Milano",
        "width_cm": 131.0,
        "depth_cm": 94.0,
        "height_cm": 138.0,
        "price": 649.5,
        "material": "Steel",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 339.9,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Artisan Premium Glass Desk Model 028",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0028",
        "brand": "Artisan",
        "width_cm": 134.0,
        "depth_cm": 96.0,
        "height_cm": 142.0,
        "price": 668.0,
        "material": "Glass",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 365.3,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Klassik Premium Laminate Desk Model 029",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0029",
        "brand": "Klassik",
        "width_cm": 137.0,
        "depth_cm": 98.0,
        "height_cm": 146.0,
        "price": 686.5,
        "material": "Laminate",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 392.0,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Studio Premium Oak Desk Model 030",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0030",
        "brand": "Studio",
        "width_cm": 140.0,
        "depth_cm": 100.0,
        "height_cm": 150.0,
        "price": 705.0,
        "material": "Oak",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 420.0,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Nordic Premium Walnut Desk Model 031",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0031",
        "brand": "Nordic",
        "width_cm": 143.0,
        "depth_cm": 102.0,
        "height_cm": 154.0,
        "price": 723.5,
        "material": "Walnut",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 449.2,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Milano Premium Steel Desk Model 032",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0032",
        "brand": "Milano",
        "width_cm": 146.0,
        "depth_cm": 104.0,
        "height_cm": 158.0,
        "price": 742.0,
        "material": "Steel",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 479.8,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Artisan Premium Glass Desk Model 033",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0033",
        "brand": "Artisan",
        "width_cm": 149.0,
        "depth_cm": 106.0,
        "height_cm": 162.0,
        "price": 760.5,
        "material": "Glass",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 511.7,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Klassik Premium Laminate Desk Model 034",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0034",
        "brand": "Klassik",
        "width_cm": 152.0,
        "depth_cm": 108.0,
        "height_cm": 166.0,
        "price": 779.0,
        "material": "Laminate",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 545.0,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Studio Premium Oak Desk Model 035",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0035",
        "brand": "Studio",
        "width_cm": 155.0,
        "depth_cm": 110.0,
        "height_cm": 170.0,
        "price": 797.5,
        "material": "Oak",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 579.7,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Nordic Premium Walnut Desk Model 036",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0036",
        "brand": "Nordic",
        "width_cm": 158.0,
        "depth_cm": 112.0,
        "height_cm": 174.0,
        "price": 816.0,
        "material": "Walnut",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 615.8,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Milano Premium Steel Desk Model 037",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0037",
        "brand": "Milano",
        "width_cm": 161.0,
        "depth_cm": 114.0,
        "height_cm": 178.0,
        "price": 834.5,
        "material": "Steel",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 653.4,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Artisan Premium Glass Desk Model 038",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0038",
        "brand": "Artisan",
        "width_cm": 164.0,
        "depth_cm": 116.0,
        "height_cm": 182.0,
        "price": 853.0,
        "material": "Glass",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 692.5,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Klassik Premium Laminate Desk Model 039",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0039",
        "brand": "Klassik",
        "width_cm": 167.0,
        "depth_cm": 118.0,
        "height_cm": 186.0,
        "price": 871.5,
        "material": "Laminate",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 733.1,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Studio Premium Oak Desk Model 040",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0040",
        "brand": "Studio",
        "width_cm": 170.0,
        "depth_cm": 120.0,
        "height_cm": 190.0,
        "price": 890.0,
        "material": "Oak",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 775.2,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Nordic Premium Walnut Desk Model 041",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0041",
        "brand": "Nordic",
        "width_cm": 173.0,
        "depth_cm": 122.0,
        "height_cm": 194.0,
        "price": 908.5,
        "material": "Walnut",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 818.9,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Milano Premium Steel Desk Model 042",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0042",
        "brand": "Milano",
        "width_cm": 176.0,
        "depth_cm": 124.0,
        "height_cm": 198.0,
        "price": 927.0,
        "material": "Steel",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 864.2,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Artisan Premium Glass Desk Model 043",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0043",
        "brand": "Artisan",
        "width_cm": 179.0,
        "depth_cm": 126.0,
        "height_cm": 202.0,
        "price": 945.5,
        "material": "Glass",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 911.2,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Klassik Premium Laminate Desk Model 044",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0044",
        "brand": "Klassik",
        "width_cm": 182.0,
        "depth_cm": 128.0,
        "height_cm": 206.0,
        "price": 964.0,
        "material": "Laminate",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 959.8,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Studio Premium Oak Desk Model 045",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0045",
        "brand": "Studio",
        "width_cm": 185.0,
        "depth_cm": 130.0,
        "height_cm": 210.0,
        "price": 982.5,
        "material": "Oak",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1010.1,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Nordic Premium Walnut Desk Model 046",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0046",
        "brand": "Nordic",
        "width_cm": 188.0,
        "depth_cm": 132.0,
        "height_cm": 214.0,
        "price": 1001.0,
        "material": "Walnut",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1062.1,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Milano Premium Steel Desk Model 047",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0047",
        "brand": "Milano",
        "width_cm": 191.0,
        "depth_cm": 134.0,
        "height_cm": 218.0,
        "price": 1019.5,
        "material": "Steel",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1115.9,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Artisan Premium Glass Desk Model 048",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0048",
        "brand": "Artisan",
        "width_cm": 194.0,
        "depth_cm": 136.0,
        "height_cm": 222.0,
        "price": 1038.0,
        "material": "Glass",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1171.4,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Klassik Premium Laminate Desk Model 049",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0049",
        "brand": "Klassik",
        "width_cm": 197.0,
        "depth_cm": 138.0,
        "height_cm": 226.0,
        "price": 1056.5,
        "material": "Laminate",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1228.8,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Studio Premium Oak Desk Model 050",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0050",
        "brand": "Studio",
        "width_cm": 200.0,
        "depth_cm": 140.0,
        "height_cm": 30.0,
        "price": 1075.0,
        "material": "Oak",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 168.0,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Nordic Premium Walnut Desk Model 051",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0051",
        "brand": "Nordic",
        "width_cm": 203.0,
        "depth_cm": 142.0,
        "height_cm": 34.0,
        "price": 1093.5,
        "material": "Walnut",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 196.0,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Milano Premium Steel Desk Model 052",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0052",
        "brand": "Milano",
        "width_cm": 206.0,
        "depth_cm": 144.0,
        "height_cm": 38.0,
        "price": 1112.0,
        "material": "Steel",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 225.4,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Artisan Premium Glass Desk Model 053",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0053",
        "brand": "Artisan",
        "width_cm": 209.0,
        "depth_cm": 146.0,
        "height_cm": 42.0,
        "price": 1130.5,
        "material": "Glass",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 256.3,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Klassik Premium Laminate Desk Model 054",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0054",
        "brand": "Klassik",
        "width_cm": 212.0,
        "depth_cm": 148.0,
        "height_cm": 46.0,
        "price": 1149.0,
        "material": "Laminate",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 288.7,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Studio Premium Oak Desk Model 055",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0055",
        "brand": "Studio",
        "width_cm": 215.0,
        "depth_cm": 150.0,
        "height_cm": 50.0,
        "price": 1167.5,
        "material": "Oak",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 322.5,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Nordic Premium Walnut Desk Model 056",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0056",
        "brand": "Nordic",
        "width_cm": 218.0,
        "depth_cm": 152.0,
        "height_cm": 54.0,
        "price": 1186.0,
        "material": "Walnut",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 357.9,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Milano Premium Steel Desk Model 057",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0057",
        "brand": "Milano",
        "width_cm": 221.0,
        "depth_cm": 154.0,
        "height_cm": 58.0,
        "price": 1204.5,
        "material": "Steel",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 394.8,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Artisan Premium Glass Desk Model 058",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0058",
        "brand": "Artisan",
        "width_cm": 224.0,
        "depth_cm": 156.0,
        "height_cm": 62.0,
        "price": 1223.0,
        "material": "Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 433.3,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Klassik Premium Laminate Desk Model 059",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0059",
        "brand": "Klassik",
        "width_cm": 227.0,
        "depth_cm": 158.0,
        "height_cm": 66.0,
        "price": 1241.5,
        "material": "Laminate",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 473.4,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Studio Premium Oak Desk Model 060",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0060",
        "brand": "Studio",
        "width_cm": 230.0,
        "depth_cm": 160.0,
        "height_cm": 70.0,
        "price": 1260.0,
        "material": "Oak",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 515.2,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Nordic Premium Walnut Desk Model 061",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0061",
        "brand": "Nordic",
        "width_cm": 233.0,
        "depth_cm": 162.0,
        "height_cm": 74.0,
        "price": 1278.5,
        "material": "Walnut",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 558.6,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Milano Premium Steel Desk Model 062",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0062",
        "brand": "Milano",
        "width_cm": 236.0,
        "depth_cm": 164.0,
        "height_cm": 78.0,
        "price": 1297.0,
        "material": "Steel",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 603.8,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Artisan Premium Glass Desk Model 063",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0063",
        "brand": "Artisan",
        "width_cm": 239.0,
        "depth_cm": 166.0,
        "height_cm": 82.0,
        "price": 1315.5,
        "material": "Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 650.7,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Klassik Premium Laminate Desk Model 064",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0064",
        "brand": "Klassik",
        "width_cm": 242.0,
        "depth_cm": 168.0,
        "height_cm": 86.0,
        "price": 1334.0,
        "material": "Laminate",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 699.3,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Studio Premium Oak Desk Model 065",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0065",
        "brand": "Studio",
        "width_cm": 245.0,
        "depth_cm": 170.0,
        "height_cm": 90.0,
        "price": 1352.5,
        "material": "Oak",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 749.7,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Nordic Premium Walnut Desk Model 066",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0066",
        "brand": "Nordic",
        "width_cm": 248.0,
        "depth_cm": 172.0,
        "height_cm": 94.0,
        "price": 1371.0,
        "material": "Walnut",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 801.9,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Milano Premium Steel Desk Model 067",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0067",
        "brand": "Milano",
        "width_cm": 251.0,
        "depth_cm": 174.0,
        "height_cm": 98.0,
        "price": 1389.5,
        "material": "Steel",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 856.0,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Artisan Premium Glass Desk Model 068",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0068",
        "brand": "Artisan",
        "width_cm": 254.0,
        "depth_cm": 176.0,
        "height_cm": 102.0,
        "price": 1408.0,
        "material": "Glass",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 912.0,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Klassik Premium Laminate Desk Model 069",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0069",
        "brand": "Klassik",
        "width_cm": 257.0,
        "depth_cm": 178.0,
        "height_cm": 106.0,
        "price": 1426.5,
        "material": "Laminate",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 969.8,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Studio Premium Oak Desk Model 070",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0070",
        "brand": "Studio",
        "width_cm": 260.0,
        "depth_cm": 180.0,
        "height_cm": 110.0,
        "price": 1445.0,
        "material": "Oak",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1029.6,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Nordic Premium Walnut Desk Model 071",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0071",
        "brand": "Nordic",
        "width_cm": 263.0,
        "depth_cm": 182.0,
        "height_cm": 114.0,
        "price": 1463.5,
        "material": "Walnut",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1091.3,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Milano Premium Steel Desk Model 072",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0072",
        "brand": "Milano",
        "width_cm": 266.0,
        "depth_cm": 184.0,
        "height_cm": 118.0,
        "price": 1482.0,
        "material": "Steel",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1155.1,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Artisan Premium Glass Desk Model 073",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0073",
        "brand": "Artisan",
        "width_cm": 269.0,
        "depth_cm": 186.0,
        "height_cm": 122.0,
        "price": 1500.5,
        "material": "Glass",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1220.8,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Klassik Premium Laminate Desk Model 074",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0074",
        "brand": "Klassik",
        "width_cm": 272.0,
        "depth_cm": 188.0,
        "height_cm": 126.0,
        "price": 1519.0,
        "material": "Laminate",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1288.6,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Studio Premium Oak Desk Model 075",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0075",
        "brand": "Studio",
        "width_cm": 275.0,
        "depth_cm": 190.0,
        "height_cm": 130.0,
        "price": 1537.5,
        "material": "Oak",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1358.5,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Nordic Premium Walnut Desk Model 076",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0076",
        "brand": "Nordic",
        "width_cm": 278.0,
        "depth_cm": 192.0,
        "height_cm": 134.0,
        "price": 1556.0,
        "material": "Walnut",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1430.5,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Milano Premium Steel Desk Model 077",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0077",
        "brand": "Milano",
        "width_cm": 281.0,
        "depth_cm": 194.0,
        "height_cm": 138.0,
        "price": 1574.5,
        "material": "Steel",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1504.6,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Artisan Premium Glass Desk Model 078",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0078",
        "brand": "Artisan",
        "width_cm": 284.0,
        "depth_cm": 196.0,
        "height_cm": 142.0,
        "price": 1593.0,
        "material": "Glass",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1580.9,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Klassik Premium Laminate Desk Model 079",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0079",
        "brand": "Klassik",
        "width_cm": 287.0,
        "depth_cm": 198.0,
        "height_cm": 146.0,
        "price": 1611.5,
        "material": "Laminate",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1659.3,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Studio Premium Oak Desk Model 080",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0080",
        "brand": "Studio",
        "width_cm": 290.0,
        "depth_cm": 200.0,
        "height_cm": 150.0,
        "price": 1630.0,
        "material": "Oak",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1740.0,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Nordic Premium Walnut Desk Model 081",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0081",
        "brand": "Nordic",
        "width_cm": 293.0,
        "depth_cm": 202.0,
        "height_cm": 154.0,
        "price": 1648.5,
        "material": "Walnut",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1822.9,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Milano Premium Steel Desk Model 082",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0082",
        "brand": "Milano",
        "width_cm": 296.0,
        "depth_cm": 204.0,
        "height_cm": 158.0,
        "price": 1667.0,
        "material": "Steel",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1908.1,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Artisan Premium Glass Desk Model 083",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0083",
        "brand": "Artisan",
        "width_cm": 299.0,
        "depth_cm": 206.0,
        "height_cm": 162.0,
        "price": 1685.5,
        "material": "Glass",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 1995.6,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Klassik Premium Laminate Desk Model 084",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0084",
        "brand": "Klassik",
        "width_cm": 52.0,
        "depth_cm": 208.0,
        "height_cm": 166.0,
        "price": 1704.0,
        "material": "Laminate",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 359.1,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Studio Premium Oak Desk Model 085",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0085",
        "brand": "Studio",
        "width_cm": 55.0,
        "depth_cm": 210.0,
        "height_cm": 170.0,
        "price": 1722.5,
        "material": "Oak",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 392.7,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Nordic Premium Walnut Desk Model 086",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0086",
        "brand": "Nordic",
        "width_cm": 58.0,
        "depth_cm": 212.0,
        "height_cm": 174.0,
        "price": 1741.0,
        "material": "Walnut",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 427.9,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Milano Premium Steel Desk Model 087",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0087",
        "brand": "Milano",
        "width_cm": 61.0,
        "depth_cm": 214.0,
        "height_cm": 178.0,
        "price": 1759.5,
        "material": "Steel",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 464.7,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Artisan Premium Glass Desk Model 088",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0088",
        "brand": "Artisan",
        "width_cm": 64.0,
        "depth_cm": 216.0,
        "height_cm": 182.0,
        "price": 1778.0,
        "material": "Glass",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 503.2,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Klassik Premium Laminate Desk Model 089",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0089",
        "brand": "Klassik",
        "width_cm": 67.0,
        "depth_cm": 218.0,
        "height_cm": 186.0,
        "price": 1796.5,
        "material": "Laminate",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 543.3,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Studio Premium Oak Desk Model 090",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0090",
        "brand": "Studio",
        "width_cm": 70.0,
        "depth_cm": 40.0,
        "height_cm": 190.0,
        "price": 1815.0,
        "material": "Oak",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 106.4,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Nordic Premium Walnut Desk Model 091",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0091",
        "brand": "Nordic",
        "width_cm": 73.0,
        "depth_cm": 42.0,
        "height_cm": 194.0,
        "price": 1833.5,
        "material": "Walnut",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 119.0,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Milano Premium Steel Desk Model 092",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0092",
        "brand": "Milano",
        "width_cm": 76.0,
        "depth_cm": 44.0,
        "height_cm": 198.0,
        "price": 1852.0,
        "material": "Steel",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 132.4,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Artisan Premium Glass Desk Model 093",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0093",
        "brand": "Artisan",
        "width_cm": 79.0,
        "depth_cm": 46.0,
        "height_cm": 202.0,
        "price": 1870.5,
        "material": "Glass",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 146.8,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Klassik Premium Laminate Desk Model 094",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0094",
        "brand": "Klassik",
        "width_cm": 82.0,
        "depth_cm": 48.0,
        "height_cm": 206.0,
        "price": 1889.0,
        "material": "Laminate",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 162.2,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Studio Premium Oak Desk Model 095",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0095",
        "brand": "Studio",
        "width_cm": 85.0,
        "depth_cm": 50.0,
        "height_cm": 210.0,
        "price": 1907.5,
        "material": "Oak",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 178.5,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Nordic Premium Walnut Desk Model 096",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0096",
        "brand": "Nordic",
        "width_cm": 88.0,
        "depth_cm": 52.0,
        "height_cm": 214.0,
        "price": 1926.0,
        "material": "Walnut",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 195.9,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Milano Premium Steel Desk Model 097",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0097",
        "brand": "Milano",
        "width_cm": 91.0,
        "depth_cm": 54.0,
        "height_cm": 218.0,
        "price": 1944.5,
        "material": "Steel",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 214.3,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Artisan Premium Glass Desk Model 098",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0098",
        "brand": "Artisan",
        "width_cm": 94.0,
        "depth_cm": 56.0,
        "height_cm": 222.0,
        "price": 1963.0,
        "material": "Glass",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 233.7,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Klassik Premium Laminate Desk Model 099",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0099",
        "brand": "Klassik",
        "width_cm": 97.0,
        "depth_cm": 58.0,
        "height_cm": 226.0,
        "price": 1981.5,
        "material": "Laminate",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 254.3,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Studio Premium Oak Desk Model 100",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0100",
        "brand": "Studio",
        "width_cm": 100.0,
        "depth_cm": 60.0,
        "height_cm": 30.0,
        "price": 2000.0,
        "material": "Oak",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 36.0,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Nordic Premium Walnut Desk Model 101",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0101",
        "brand": "Nordic",
        "width_cm": 103.0,
        "depth_cm": 62.0,
        "height_cm": 34.0,
        "price": 2018.5,
        "material": "Walnut",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 43.4,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Milano Premium Steel Desk Model 102",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0102",
        "brand": "Milano",
        "width_cm": 106.0,
        "depth_cm": 64.0,
        "height_cm": 38.0,
        "price": 2037.0,
        "material": "Steel",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 51.6,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Artisan Premium Glass Desk Model 103",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0103",
        "brand": "Artisan",
        "width_cm": 109.0,
        "depth_cm": 66.0,
        "height_cm": 42.0,
        "price": 2055.5,
        "material": "Glass",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 60.4,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Klassik Premium Laminate Desk Model 104",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0104",
        "brand": "Klassik",
        "width_cm": 112.0,
        "depth_cm": 68.0,
        "height_cm": 46.0,
        "price": 2074.0,
        "material": "Laminate",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 70.1,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Studio Premium Oak Desk Model 105",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0105",
        "brand": "Studio",
        "width_cm": 115.0,
        "depth_cm": 70.0,
        "height_cm": 50.0,
        "price": 2092.5,
        "material": "Oak",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 80.5,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Nordic Premium Walnut Desk Model 106",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0106",
        "brand": "Nordic",
        "width_cm": 118.0,
        "depth_cm": 72.0,
        "height_cm": 54.0,
        "price": 2111.0,
        "material": "Walnut",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 91.8,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Milano Premium Steel Desk Model 107",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0107",
        "brand": "Milano",
        "width_cm": 121.0,
        "depth_cm": 74.0,
        "height_cm": 58.0,
        "price": 2129.5,
        "material": "Steel",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 103.9,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Artisan Premium Glass Desk Model 108",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0108",
        "brand": "Artisan",
        "width_cm": 124.0,
        "depth_cm": 76.0,
        "height_cm": 62.0,
        "price": 2148.0,
        "material": "Glass",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 116.9,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Klassik Premium Laminate Desk Model 109",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0109",
        "brand": "Klassik",
        "width_cm": 127.0,
        "depth_cm": 78.0,
        "height_cm": 66.0,
        "price": 2166.5,
        "material": "Laminate",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 130.8,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Studio Premium Oak Desk Model 110",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0110",
        "brand": "Studio",
        "width_cm": 130.0,
        "depth_cm": 80.0,
        "height_cm": 70.0,
        "price": 2185.0,
        "material": "Oak",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 145.6,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Nordic Premium Walnut Desk Model 111",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0111",
        "brand": "Nordic",
        "width_cm": 133.0,
        "depth_cm": 82.0,
        "height_cm": 74.0,
        "price": 2203.5,
        "material": "Walnut",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 161.4,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Milano Premium Steel Desk Model 112",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0112",
        "brand": "Milano",
        "width_cm": 136.0,
        "depth_cm": 84.0,
        "height_cm": 78.0,
        "price": 2222.0,
        "material": "Steel",
        "color_options_json": '["#27AE60", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 178.2,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Artisan Premium Glass Desk Model 113",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0113",
        "brand": "Artisan",
        "width_cm": 139.0,
        "depth_cm": 86.0,
        "height_cm": 82.0,
        "price": 2240.5,
        "material": "Glass",
        "color_options_json": '["#8E44AD", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 196.0,
        "assembly_required": False,
        "warranty_years": 3,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
    {
        "name": "Klassik Premium Laminate Desk Model 114",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0114",
        "brand": "Klassik",
        "width_cm": 142.0,
        "depth_cm": 88.0,
        "height_cm": 86.0,
        "price": 2259.0,
        "material": "Laminate",
        "color_options_json": '["#D35400", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 214.9,
        "assembly_required": True,
        "warranty_years": 4,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.3
    },
    {
        "name": "Studio Premium Oak Desk Model 115",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0115",
        "brand": "Studio",
        "width_cm": 145.0,
        "depth_cm": 90.0,
        "height_cm": 90.0,
        "price": 2277.5,
        "material": "Oak",
        "color_options_json": '["#2980B9", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 234.9,
        "assembly_required": False,
        "warranty_years": 5,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.4
    },
    {
        "name": "Nordic Premium Walnut Desk Model 116",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0116",
        "brand": "Nordic",
        "width_cm": 148.0,
        "depth_cm": 92.0,
        "height_cm": 94.0,
        "price": 2296.0,
        "material": "Walnut",
        "color_options_json": '["#7D6608", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium walnut by Nordic. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 256.0,
        "assembly_required": True,
        "warranty_years": 6,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.5
    },
    {
        "name": "Milano Premium Steel Desk Model 117",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0117",
        "brand": "Milano",
        "width_cm": 151.0,
        "depth_cm": 94.0,
        "height_cm": 98.0,
        "price": 2314.5,
        "material": "Steel",
        "color_options_json": '["#1C2833", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium steel by Milano. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 278.2,
        "assembly_required": False,
        "warranty_years": 7,
        "sustainability_rating": "LEED Gold Certified Class 2",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.6
    },
    {
        "name": "Artisan Premium Glass Desk Model 118",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0118",
        "brand": "Artisan",
        "width_cm": 154.0,
        "depth_cm": 96.0,
        "height_cm": 102.0,
        "price": 2333.0,
        "material": "Glass",
        "color_options_json": '["#F5CBA7", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium glass by Artisan. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 301.6,
        "assembly_required": True,
        "warranty_years": 8,
        "sustainability_rating": "LEED Gold Certified Class 3",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.7
    },
    {
        "name": "Klassik Premium Laminate Desk Model 119",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0119",
        "brand": "Klassik",
        "width_cm": 157.0,
        "depth_cm": 98.0,
        "height_cm": 106.0,
        "price": 2351.5,
        "material": "Laminate",
        "color_options_json": '["#FFFFFF", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium laminate by Klassik. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 326.2,
        "assembly_required": False,
        "warranty_years": 9,
        "sustainability_rating": "LEED Gold Certified Class 4",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.1
    },
    {
        "name": "Studio Premium Oak Desk Model 120",
        "category": "Office",
        "subcategory": "Desks",
        "sku": "SKU-OFF-DES-0120",
        "brand": "Studio",
        "width_cm": 160.0,
        "depth_cm": 100.0,
        "height_cm": 110.0,
        "price": 2370.0,
        "material": "Oak",
        "color_options_json": '["#5D6D7E", "#FFFFFF", "#1C2833"]',
        "description": "High quality enterprise office desks crafted with premium oak by Studio. Designed for durability, ergonomic comfort, and modern architectural aesthetics.",
        "weight_kg": 352.0,
        "assembly_required": True,
        "warranty_years": 2,
        "sustainability_rating": "LEED Gold Certified Class 1",
        "cad_symbol_type": "furniture_desks",
        "acoustic_absorption_coef": 0.2
    },
]

def get_all_items():
    """Return list of all catalog items for Office Desks."""
    return CATALOG_ITEMS_OFFICE_DESKS

def get_items_by_brand(brand_name):
    """Filter catalog items by brand."""
    return [item for item in CATALOG_ITEMS_OFFICE_DESKS if item["brand"].lower() == brand_name.lower()]

def get_items_by_material(material_name):
    """Filter catalog items by material."""
    return [item for item in CATALOG_ITEMS_OFFICE_DESKS if item["material"].lower() == material_name.lower()]

def get_items_in_price_range(min_price, max_price):
    """Filter catalog items within price range."""
    return [item for item in CATALOG_ITEMS_OFFICE_DESKS if min_price <= item["price"] <= max_price]
